### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by cornbread-eater**

### CODE REVIEW

**Review by FahimFBA — COMMENTED** [review]
This doesn't make any sense.

**Comment by FahimFBA** [comment]
This type of pull request doesn't make any sense. Please don't spam by adding irrelevant spaces, and so on.

**Comment by cornbread-eater** [comment]
oh sorry i didnt mean to spam. its my bad

**Comment by FahimFBA** [comment]
> oh sorry i didnt mean to spam. its my bad

It's okay. Please try to contribute on relevant topics on other issues.

**Pull request closed without merging**
